# Automatically created by the clamav-freshclam postinst
# Comments will get lost when you reconfigure the clamav-freshclam package

DatabaseOwner clamav
UpdateLogFile /var/log/clamav/freshclam.log
LogVerbose false
LogSyslog false
LogFacility LOG_LOCAL6
LogFileMaxSize 0
LogRotate true
LogTime true
Foreground false
Debug false
MaxAttempts 5
DatabaseDirectory /var/lib/clamav
DNSDatabaseInfo current.cvd.clamav.net
ConnectTimeout 30
ReceiveTimeout 0
TestDatabases yes
ScriptedUpdates yes
CompressLocalDatabase no
Bytecode true
NotifyClamd /etc/clamav/clamd.conf
# Check for new database {{ _check_database_days }} times a day
Checks {{ _check_database_days }}

# Définir l'URL des MAJ des bases de l'antivirus
{% if clamav_private_mirror is string and clamav_private_mirror | trim | length > 0 %}
DatabaseMirror {{ _clamav_private_mirror }}
{% else %}
DatabaseMirror db.local.clamav.net
DatabaseMirror database.clamav.net
{% endif %}
