---

cyrus_share:
  hosts:
    cyrus_murder:
      ansible_connection: docker
    
    cyrus_frontend_01:
      ansible_connection: docker

    cyrus_frontend_02:
      ansible_connection: docker

    cyrus_backend_01:
      ansible_connection: docker

    cyrus_backend_02:
      ansible_connection: docker

cyrus_share_save:
  hosts:
    cyrus_save_backend_01:
      ansible_connection: docker

    cyrus_save_backend_02:
      ansible_connection: docker

smtp_postfix:
  hosts:
    smtp_postfix_01:
      ansible_connection: docker

proxy_dovecot:
  hosts:
    proxy_dovecot_01:
      ansible_connection: docker

ldap:
  hosts:
    ldap_server:
      ansible_connection: docker

keycloak:
  hosts:
    keycloak_server:
      ansible_connection: docker
