- name: " Copie des fichiers LDIF"
  template:
    src: "{{ item.source }}"
    dest: "{{ item.destination}}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    # - { source: 'ldifs/base.ldif', destination: '/tmp/base.ldif', owner: 'openldap', group: 'openldap', mode: '0644' }
    ## Base déjà créée par le conteneur LDAP au démarrage
    - { source: 'ldifs/users.ldif', destination: '/tmp/users.ldif', owner: 'openldap', group: 'openldap', mode: '0644' }
    - { source: 'ldifs/units.ldif', destination: '/tmp/units.ldif', owner: 'openldap', group: 'openldap', mode: '0644' }

- name: " Import des fichiers LDIF dans l'annuaire LDAP"
  command: "ldapadd -x -D '{{ ldap_admin_dn }}' -w '{{ ldap_admin_password }}' -f {{ item }}"
  with_items:
    # - /tmp/base.ldif
    - /tmp/users.ldif
    - /tmp/units.ldif
  