
ARG PRIVATE_REGISTRY=""
ARG IMAGE="debian"
ARG TAG="13.2-slim"

FROM ${PRIVATE_REGISTRY}${IMAGE}:${TAG}

LABEL autor="matyas-cyril"

# %COPY_SRC_CMD%
# %COPY_GPG_CMD%

RUN apt-get update && apt-get -y upgrade && \
    apt-get install -y man-db htop db-util locate gettext-base systemctl

RUN apt-get install -y --no-install-recommends iproute2 netcat-traditional telnet rlwrap \
     inetutils-ping dnsutils swaks tree rlwrap vim vim-common sasl2-bin syslog-ng

RUN apt-get autoremove -y

RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/log/*

COPY --chown=root:root syslog-ng.conf /etc/syslog-ng/syslog-ng.conf
COPY --chown=root:root syslog-ng.default /etc/default/syslog-ng

RUN echo 'service syslog-ng start; while [ 1 ]; do sleep 1 ;done;' > /loop_inf.sh && chmod +x /loop_inf.sh

CMD /loop_inf.sh
