---

- name: "Générer les fichiers pour Postfix - Backend"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: no
  with_items:
    - { src: 'backend/postfix/main.conf', dest: '/etc/postfix/main.cf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'backend/postfix/master.conf', dest: '/etc/postfix/master.cf', owner: 'root', group: 'root', mode: '0644' }
  notify:
    restart_postfix