---

- name: "Générer les fichiers pour Postfix - Frontend"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: no
  with_items:
    - { src: 'frontend/postfix/main.conf', dest: '/etc/postfix/main.cf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'frontend/postfix/master.conf', dest: '/etc/postfix/master.cf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'domains.list', dest: '/etc/postfix/domains.list', owner: 'root', group: 'root', mode: '0644' }
  notify:
    restart_postfix

- name: "Générer les fichiers pour Cyrus Imapd - Frontend"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: no
  with_items:
    - { src: 'frontend/cyrus/cyrus.conf', dest: '/etc/cyrus.conf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'frontend/cyrus/imapd.conf', dest: '/etc/imapd.conf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'frontend/cyrus/imapd-ext.conf', dest: '/etc/imapd-ext.conf', owner: 'root', group: 'root', mode: '0644' }
  notify:
    restart_cyrus

- name: "Activer Cyrus Imapd Frontend au démarrage"
  service:
    name: cyrus-imapd
    state: started
    enabled: yes
