---

- block:
    - name: "Redémarrer Cyrus-IMAP"
      command: /etc/init.d/cyrus-imapd restart
      register: restart_result
      ignore_errors: yes # Erreurs contrôlées !!!!
  rescue:
    - name: "Vérifier le statut du service"
      command: /etc/init.d/cyrus-imapd status
      register: service_status
      failed_when: false
  when:
    inventory_hostname | upper is regex("^CYRUS_\S+END_\d+$")
  tags:
    - sample

- name: "Création de mailbox sur le backend 01"
  shell: echo "cm {{ item.dir }}{{ item.mailbox }} {{item.partition}}" | cyradm -u cyrus --password Cyrus localhost
  with_items:
    - { mailbox: 'bal-org-01', partition: 'org', dir: 'user/' }
    - { mailbox: 'bal-org-02', partition: 'org', dir: 'user/' }
    - { mailbox: 'ali', partition: 'default', dir: 'user/' }
    - { mailbox: 'benoit', partition: 'default', dir: 'user/' }
    - { mailbox: 'cyril', partition: 'default', dir: 'user/' }
    - { mailbox: 'julien', partition: 'default', dir: 'user/' }
    - { mailbox: 'bal-spe-53', partition: 'spe', dir: '' }
  when:
    inventory_hostname | upper is regex("^CYRUS_BACKEND_01$")
  tags:
    - sample   

- name: "Création de mailbox backend 02"
  shell: echo "cm {{ item.dir }}{{ item.mailbox }} {{item.partition}}" | cyradm -u cyrus --password Cyrus localhost
  with_items:
    - { mailbox: 'bal-org-03', partition: 'org', dir: 'user/' }
    - { mailbox: 'jessy', partition: 'default', dir: 'user/' }
    - { mailbox: 'olivier', partition: 'default', dir: 'user/' }
    - { mailbox: 'pepito', partition: 'default', dir: 'user/' }
    - { mailbox: 'samy', partition: 'default', dir: 'user/' }
    - { mailbox: 'bal-spe-51', partition: 'spe', dir: '' }
    - { mailbox: 'bal-spe-52', partition: 'spe', dir: '' }
  when:
    inventory_hostname | upper is regex("^CYRUS_BACKEND_02$")
  tags:
    - sample

- name: "Établir un quota"
  shell: echo "sq {{ item.dir }}{{ item.mailbox }} {{ item.quota }}" | cyradm -u cyrus --password Cyrus localhost
  with_items:
    - { mailbox: 'ali', quota: 50000, dir: 'user/' }
    - { mailbox: 'benoit', quota: 50000, dir: 'user/' }
    - { mailbox: 'cyril', quota: 50000, dir: 'user/' }
    - { mailbox: 'julien', quota: 50000, dir: 'user/' }
    - { mailbox: 'jessy', quota: 50000, dir: 'user/' }
    - { mailbox: 'olivier', quota: 50000, dir: 'user/' }
    - { mailbox: 'pepito', quota: 50000, dir: 'user/' }
    - { mailbox: 'samy', quota: 50000, dir: 'user/' }
    - { mailbox: 'bal-org-01', quota: 50000, dir: 'user/' }
    - { mailbox: 'bal-org-02', quota: 50000, dir: 'user/' }
    - { mailbox: 'bal-org-03', quota: 50000, dir: 'user/' }
    - { mailbox: 'bal-spe-51', quota: 50000, dir: '' }
    - { mailbox: 'bal-spe-52', quota: 50000, dir: '' }
    - { mailbox: 'bal-spe-53', quota: 50000, dir: '' }
  when:
    inventory_hostname | upper is regex("^CYRUS_FRONTEND_01$")
  tags:
    - sample

- name: "Mettre des droits sur les BAL Org"
  shell: echo "sam user/{{ item.mailbox }} {{ item.user }} {{ item.acl }}" | cyradm -u cyrus --password Cyrus localhost
  with_items:
    - { mailbox: 'bal-org-03', user: 'ali', acl: 'all' }
    - { mailbox: 'bal-org-03', user: 'pepito', acl: 'all' }
    - { mailbox: 'bal-org-01', user: 'cyril', acl: 'all' }
    - { mailbox: 'bal-org-01', user: 'samy', acl: 'all' }
    - { mailbox: 'bal-org-02', user: 'benoit', acl: 'all' }
    - { mailbox: 'bal-org-02', user: 'cyril', acl: 'all' }
    - { mailbox: 'bal-org-02', user: 'olivier', acl: 'all' }
    - { mailbox: 'bal-org-03', user: 'samy', acl: 'all' }
    - { mailbox: 'bal-org-03', user: 'olivier', acl: 'all' }    
    - { mailbox: 'bal-org-03', user: 'jessy', acl: 'all' }  
    - { mailbox: 'bal-org-03', user: 'julien', acl: 'all' }    
  when:
    inventory_hostname | upper is regex("^CYRUS_FRONTEND_02$")
  tags:
    - sample

- name: "Mettre des droits sur les BAL Spe"
  shell: echo "sam {{ item.mailbox }} {{ item.user }} {{ item.acl }}" | cyradm -u cyrus --password Cyrus localhost
  with_items:
    - { mailbox: 'bal-spe-51', user: 'cyril', acl: 'all' }
    - { mailbox: 'bal-spe-51', user: 'samy', acl: 'all' }
    - { mailbox: 'bal-spe-52', user: 'benoit', acl: 'all' }
    - { mailbox: 'bal-spe-52', user: 'cyril', acl: 'all' }
    - { mailbox: 'bal-spe-52', user: 'olivier', acl: 'all' }
    - { mailbox: 'bal-spe-53', user: 'samy', acl: 'all' }
    - { mailbox: 'bal-spe-53', user: 'olivier', acl: 'all' }    
    - { mailbox: 'bal-spe-53', user: 'jessy', acl: 'all' }  
    - { mailbox: 'bal-spe-53', user: 'julien', acl: 'all' }
    - { mailbox: 'bal-spe-52', user: 'ali', acl: 'all' }
    - { mailbox: 'bal-spe-53', user: 'pepito', acl: 'all' }   
  when:
    inventory_hostname | upper is regex("^CYRUS_FRONTEND_02$")
  tags:
    - sample