---

- block:
    - name: "Redémarrer Cyrus-IMAP"
      systemd:
        name: cyrus-imapd
        state: restarted
        enabled: yes
      register: restart_result
  rescue:
    - name: "Vérifier le statut du service"
      command: systemctl status cyrus-imapd
      register: service_status
      failed_when: false
  when:
    inventory_hostname | upper is regex("^CYRUS_\S+END_\d+$")
  tags:
    - sample  

- name: "Ajout des utilisaturs de test pour l'authentification"
  shell: echo -n "{{ item.password }}" | saslpasswd2 -p -c "{{ item.username }}"
  with_items:
    - { username: 'ali', password: 'Ali' }
    - { username: 'benoit', password: 'Benoit' }
    - { username: 'cyril', password: 'Cyril' }
    - { username: 'julien', password: 'Julien' }
    - { username: 'jessy', password: 'Jessy' }
    - { username: 'olivier', password: 'Olivier' }
    - { username: 'pepito', password: 'Pepito' }
    - { username: 'samy', password: 'Samy' }
  when:
    inventory_hostname | upper is regex("^CYRUS_FRONTEND_\d+$")
  tags:
    - sample

- name: "Création de mailbox sur le backend 01"
  shell: echo "cm user/{{ item.mailbox }} {{item.partition}}" | cyradm -u cyrus --password Cyrus localhost
  with_items:
    - { mailbox: 'bal-org-01', partition: 'org' }
    - { mailbox: 'bal-org-02', partition: 'org' }
    - { mailbox: 'ali', partition: 'default' }
    - { mailbox: 'benoit', partition: 'default' }
    - { mailbox: 'cyril', partition: 'default' }
    - { mailbox: 'julien', partition: 'default' }
    - { mailbox: 'bal-spe-53', partition: 'spe' }
  when:
    inventory_hostname | upper is regex("^CYRUS_BACKEND_01$")
  tags:
    - sample   

- name: "Création de mailbox backend 02"
  shell: echo "cm user/{{ item.mailbox }} {{item.partition}}" | cyradm -u cyrus --password Cyrus localhost
  with_items:
    - { mailbox: 'bal-org-03', partition: 'org' }
    - { mailbox: 'jessy', partition: 'default' }
    - { mailbox: 'olivier', partition: 'default' }
    - { mailbox: 'pepito', partition: 'default' }
    - { mailbox: 'samy', partition: 'default' }
    - { mailbox: 'bal-spe-51', partition: 'spe' }
    - { mailbox: 'bal-spe-52', partition: 'spe' }
  when:
    inventory_hostname | upper is regex("^CYRUS_BACKEND_02$")
  tags:
    - sample

- name: "Établir un quota"
  shell: echo "sq user/{{ item.mailbox }} {{ item.quota }}" | cyradm -u cyrus --password Cyrus localhost
  with_items:
    - { mailbox: 'ali', quota: 50000 }
    - { mailbox: 'benoit', quota: 50000 }
    - { mailbox: 'cyril', quota: 50000 }
    - { mailbox: 'julien', quota: 50000 }
    - { mailbox: 'jessy', quota: 50000 }
    - { mailbox: 'olivier', quota: 50000 }
    - { mailbox: 'pepito', quota: 50000 }
    - { mailbox: 'samy', quota: 50000 }
    - { mailbox: 'bal-org-01', quota: 50000 }
    - { mailbox: 'bal-org-02', quota: 50000 }
    - { mailbox: 'bal-org-03', quota: 50000 }
    - { mailbox: 'bal-spe-51', quota: 50000 }
    - { mailbox: 'bal-spe-52', quota: 50000 }
    - { mailbox: 'bal-spe-53', quota: 50000 }
  when:
    inventory_hostname | upper is regex("^CYRUS_FRONTEND_01$")
  tags:
    - sample

- name: "Mettre des droits sur les BAL Org"
  shell: echo "sam user/{{ item.mailbox }} {{ item.user }} {{ item.acl }}" | cyradm -u cyrus --password Cyrus localhost
  with_items:
    - { mailbox: 'bal-org-03', user: 'ali', acl: 'all' }
    - { mailbox: 'bal-org-03', user: 'pepito', acl: 'all' }
    - { mailbox: 'bal-org-01', user: 'cyril', acl: 'all' }
    - { mailbox: 'bal-org-01', user: 'samy', acl: 'all' }
    - { mailbox: 'bal-org-02', user: 'benoit', acl: 'all' }
    - { mailbox: 'bal-org-02', user: 'cyril', acl: 'all' }
    - { mailbox: 'bal-org-02', user: 'olivier', acl: 'all' }
    - { mailbox: 'bal-org-03', user: 'samy', acl: 'all' }
    - { mailbox: 'bal-org-03', user: 'olivier', acl: 'all' }    
    - { mailbox: 'bal-org-03', user: 'jessy', acl: 'all' }  
    - { mailbox: 'bal-org-03', user: 'julien', acl: 'all' }    
  when:
    inventory_hostname | upper is regex("^CYRUS_FRONTEND_02$")
  tags:
    - sample

- name: "Mettre des droits sur les BAL Spe"
  shell: echo "sam user/{{ item.mailbox }} {{ item.user }} {{ item.acl }}" | cyradm -u cyrus --password Cyrus localhost
  with_items:
    - { mailbox: 'bal-spe-51', user: 'cyril', acl: 'all' }
    - { mailbox: 'bal-spe-51', user: 'samy', acl: 'all' }
    - { mailbox: 'bal-spe-52', user: 'benoit', acl: 'all' }
    - { mailbox: 'bal-spe-52', user: 'cyril', acl: 'all' }
    - { mailbox: 'bal-spe-52', user: 'olivier', acl: 'all' }
    - { mailbox: 'bal-spe-53', user: 'samy', acl: 'all' }
    - { mailbox: 'bal-spe-53', user: 'olivier', acl: 'all' }    
    - { mailbox: 'bal-spe-53', user: 'jessy', acl: 'all' }  
    - { mailbox: 'bal-spe-53', user: 'julien', acl: 'all' }
    - { mailbox: 'bal-spe-52', user: 'ali', acl: 'all' }
    - { mailbox: 'bal-spe-53', user: 'pepito', acl: 'all' }   
  when:
    inventory_hostname | upper is regex("^CYRUS_FRONTEND_02$")
  tags:
    - sample