---

- hosts: localhost
  gather_facts: no

  tasks:
    - name: "Démarrer les services Docker de la plateforme"
      command: docker compose -f ../Docker/plateform.yml up -d
      tags:
        - always

- hosts: cyrus_share
  gather_facts: yes

  tasks:
    - name: "Installer Cyrus / Postfix - Messagerie partagée"
      block:
        - include_role:
            name: msg-shared
          tags:
            - install
      rescue:
        - debug:
            msg: "Erreur lors de l'installation de la Messagerie partagée"