---
# tasks file for msg-smtp
- name: "Créer le répertoire /etc/postfix/sasl"
  file:
    path: /etc/postfix/sasl
    state: directory
    owner: root
    group: root
    mode: 0644
  tags:
    - install

- name: "Générer les fichiers pour Postfix"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: no
  with_items:
    - { src: 'main.conf', dest: '/etc/postfix/main.cf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'master.conf', dest: '/etc/postfix/master.cf', owner: 'root', group: 'root', mode: '0644' }
    - { src: 'domains.list', dest: '/etc/postfix/domains.list', owner: 'root', group: 'root', mode: '0644' }
  notify:
    restart_postfix
  tags:
    - install

- name: "Copier les fichiers Postfix nécessitant une génération db, cdb..."
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: no
  with_items:
    - { src: 'transport_to_mbx', dest: '/etc/postfix/transport_to_mbx', owner: 'root', group: 'root', mode: '0644' }
  register:
    rslt_postfix_file
  tags:
    - install

- name: "Générer les db, cdb.. des fichiers Postfix modifiés"
  command: "postmap {{ item.type }}:{{ item.dest }}"
  when: rslt_postfix_file.changed
  with_items:
    - { dest: '/etc/postfix/transport_to_mbx', type: 'cdb' }
  notify:
    restart_postfix
  tags:
    - install
