#SPDX-License-Identifier: MIT-0
---
# handlers file for msg-shared
- name: restart_postfix
  service:
    name: postfix
    state: restarted

- name: restart_cyrus
  service:
    name: cyrus-imapd
    state: restarted
