---
# tasks file for proxy-dovecot

- name: "Tâches dovecot"
  import_tasks:
    file: dovecot.yml
  tags:
    - always

- name: "Utilisateurs proxy dovecot"
  import_tasks:
    file: passwd.yml
  tags:
    - always